name: Translate Documentation Action
author: Ephraim Atta-Duncan
description: Translate the Documentation to another language

inputs:
  LANG:
    description: 'The Language you want to translate to'
    required: false
    default: 'zh-CN'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: book-open
  color: black
